### ISSUE TITLE
No connection adapters were found for ''https://asmhentai.com/gallery/274028/''

### ISSUE THREAD

**Issue by Raven-Lee** [AnnieBrighton/asmhentai#1]
```
asmhentai-master>asmhentai.py 'https://asmhentai.com/gallery/274028/'
Traceback (most recent call last):
  File "D:\asmhentai-master\asmhentai.py", line 189, in <module>
    download_pics(url)
  File "D:\asmhentai-master\asmhentai.py", line 128, in download_pics
    index = lxml.etree.HTML(req.get(url).text)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for ''https://asmhentai.com/gallery/274028/''
```

使ってみたらこういうのを出ました。何かのパッケージが足りないでしょうか？

環境：Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32

**Comment by Raven-Lee** [comment]
あしたLinuxでやってみます

**Comment by AnnieBrighton** [comment]
https://asmhentai.com/g/274028/ の誤りでは？
COMIC 快楽天 2019年11月号 [DL版] が対象ならば

**Comment by Raven-Lee** [comment]
Linuxでうまくやりました。
ありがとうございます。

Windows環境で、また調整してみます
